import { useTheme } from "next-themes";
import Head from "next/head";

export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Next-Tailwind-Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-96 flex flex-col justify-center items-center">
        <p className="text-3xl text-center">
          Next-Tailwind-Starter with dark mode
        </p>
        <button
          className="dark:bg-black bg-white font-bold text-xl p-4 m-4 border-2 border-black dark:border-white rounded-lg"
          onClick={() => {
            setTheme(theme === "dark" ? "light" : "dark");
          }}
        >
          Change Theme
        </button>
      </div>
    </>
  );
}
